version: 2

builds:
  - id: nuon-ext-api
    main: .
    binary: nuon-ext-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: nuon-ext-api
    builds:
      - nuon-ext-api
    format: tar.gz
    name_template: "nuon-ext-api-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
